### PR TITLE
Pop-up task

### PR DESCRIPTION
**Pull request by babayK0**
### Pop-up

[Demo](https://babayk0.github.io/pop-up/) |
[Code base](https://github.com/babayK0/pop-up)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by A-Ostrovnyy** [comment]
Why you closed your PR?

**Comment by babayK0** [comment]
@A-Ostrovnyy i will try to fix google warnings

**Comment by A-Ostrovnyy** [comment]
> @A-Ostrovnyy i will try to fix google warnings

Ok, will be waiting for your new PR.

**Comment by babayK0** [comment]
@A-Ostrovnyy I'll do it soon.

**Comment by babayK0** [comment]
@A-Ostrovnyy created a new "pop up" repository, and ask  google to cancel warning for my githhub pages. What do you think, is it enough ?

**Comment by A-Ostrovnyy** [comment]
Writing to Google was unnecessary. 
>:warning: Google-Warning

>
>The above may happen if you:
>- use word "google" in
> - your project/repo name
>  - any urls
> - in css selectors
>  - in HTML elements ids (including created with JS) or elsewhere across HTML
> - replicate Google design (layout structure, styles etc)
> - use Google icons

>Change pop-up layout and styling, use different icons (or tamper them in graphic editor) and service names, so that Google won't suspect you in attempt to mimic Google services and/or steal your visitors Google credentials.

**Pull request closed without merging**
