### PR TITLE
Task 6.  Document Object Model

### PR DESCRIPTION
**Pull request by babayK0**
### DOM

[Demo](https://babayk0.github.io/) |
[Code base](https://github.com/babayK0/babayK0.github.io)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@babayK0 Please, change PR title so it gives an idea of what's inside. Just look at other PRs titles for reference.

image

**Comment by babayK0** [comment]
@OleksiyRudenko, I changed the PR title. Is it better now?

**Comment by OleksiyRudenko** [comment]
@babayK0 Thanks! It is **clear** now.

**Comment by AMashoshyna** [comment]
Hi @babayK0! Looks very nice! Let's fix some things.

First of all, __code formatting & code style__:
- Please check all indentations, empty lines and inconsistent white spaces. You can do it by hand or use your IDE's built-in code formatter
- Naming: general convention in JavaScript is to use camelCase for variable names (`gettitles` => `getTitles`). Function name should start with a verb (`active` => `updateInactive` maybe? Not sure about this one)
- Variable names containing just one letter are ok only for loop iterators or indices

__Event delegation__:
Adding event listeners in a loop is very ineffective. Please add one event listener to containing element instead.

__Controlled identifiers__:
Generally you don't want to rely on layout details in your code. Let's say one day you will change you layout and put `h3` instead of `h2`. Then you would need to rewrite function `changeActive` too, because it matches the elements by innerHTML. Common way to handle such situations is to add unique identifiers like ids or names.

I'll come up with some more comments later, but let's do it in steps.

**Comment by babayK0** [comment]
@AMashoshyna Hi, I think that i corrected all the errors. I apologize for not replying for so long.There were certain reasons.Thank you for the review.

**Comment by babayK0** [comment]
@AMashoshyna Thank you, especially for the second comment =) Nothing bad if I made a mistake when writing a commit? (i wanted to write "adding")

**Comment by AMashoshyna** [comment]
Typo is ok, but generally you can fix you last commit (e.g. change commit message or add more files to the commit) with `git commit --amend`. With earlier commit it is trickier, you would need to rebase.
Your PR looks good to merge!

**Pull request merged**
