### PR TITLE
Tiny js world

### PR DESCRIPTION
**Pull request by Karasb888**
### Tiny-js-world (pre oop)

https://github.com/Karasb888/a-tiny-JS-world
https://karasb888.github.io/a-tiny-JS-world/

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by Karasb888** [comment]
Again i have same problems with commit and branches, like in https://github.com/kottans/frontend-2019-homeworks/pull/41 . What am I do wrong? I remove tine-js-world branch, pull master and create new tiny-js-world branch from master....=)

**Comment by OleksiyRudenko** [comment]
@Karasb888 From your [fork](https://github.com/Karasb888/frontend-2019-homeworks/branches) I can see there is a single branch on remote. So, I assume you developed `DOM task` while on `master`. 

Is the above correct?

If yes then your local master was well ahead of original repo `master` at the moment you branched off `tiny-js-world`, so the diff includes all commits between your current `tiny-js-world` tip and **original** repo `master`.

To fix the situation yo need to branch off now and in the future from `upstream/master`, which is in sync with this **original** repo, rather than from your local `master`. This makes things more complicated but that's the fee for not keeping `master` strictly in sync with upstream repo.

If you need any clarifications on the above or any help, please, let me know.

**Comment by Karasb888** [comment]
When I try to fix my issue, I delete dom-js-task branch from fork and local guided by  https://gist.github.com/OleksiyRudenko/236c3046fbba028e0555fa847dae7001 (in end, paragraph 'Cleaning up"). If i correct understand you, I need to:delete tiny-js-world, branch, set upstream of my master branch to original repo, pull, and create tiny-js-world branch from master?

**Comment by OleksiyRudenko** [comment]
@Karasb888 Unfortunately the instruction above doesn't offer methods to fix things.

Many people face similar situation. So, I gonna draft a short guide on this type of fixing. And will ask you to test it. Please, hold on.

**Comment by Karasb888** [comment]
Thanks a lot)

**Comment by OleksiyRudenko** [comment]
@Karasb888  Here we go. Please, check this [contribution issues fixing guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b). Please, let me know if anything goes wrong.

You will most likely need to open a new PR as this one will get closed.

**Comment by Karasb888** [comment]
Close for fix and clearing up commits/branch history.

**Pull request closed without merging**
