### PR TITLE
Html css popup

### PR DESCRIPTION
**Pull request by RomanovAleksander**
### HTML-CSS-Popup

[Demo](https://romanovaleksander.github.io/HTML-CSS-Popup/) |
[Code base](https://github.com/RomanovAleksander/HTML-CSS-Popup)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by RomanovAleksander** [comment]
Done. Please, review.

**Comment by A-Ostrovnyy** [comment]
Can you add `outline` or `border` for more visual identification? Current styles on `:focus` state hard to see to people with problematic vision.

**Comment by RomanovAleksander** [comment]
Ok, I will fix it later.

**Comment by RomanovAleksander** [comment]
I wanted to make it beautiful, so I didn't use border everywhere. Please, review.

**Comment by A-Ostrovnyy** [comment]
Focus state uses people with vision problems, regular people don't use it.
Color changing not enough. Most people with problematic vision can't see the color changing they need more obvious sign. Also, add outline/ border to popups items on focus.

**Comment by RomanovAleksander** [comment]
Done

**Comment by A-Ostrovnyy** [comment]
Nice work!

**Pull request merged**
