### PR TITLE
Weather componental

### PR DESCRIPTION
**Pull request by rrrds**
### Weather componental

[Demo](https://rrrds.github.io/weather-componental/) |
[Code base](https://github.com/rrrds/weather-componental)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by rrrds** [comment]
JSX-like template parser - **done**

**Comment by rrrds** [comment]
@AMashoshyna should I upload all sources from original repo into PR?

**Comment by AMashoshyna** [comment]
@rrrds Yes, it would be very convenient.

**Comment by rrrds** [comment]
@AMashoshyna Done! All sources uploaded.

**Pull request closed without merging**
