### PR TITLE
A tiny js world

### PR DESCRIPTION
**Pull request by allykrupina**
### OOP practice (A tiny js world-2)

[Demo](https://allykrupina.github.io/a-tiny-js-world/) |
[Code base](https://github.com/allykrupina/allykrupina.github.io/tree/master/a-tiny-js-world)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by allykrupina** [comment]
@OleksiyRudenko Okay, then should I close this pull request before creating a brand new branch for this task?

**Comment by OleksiyRudenko** [comment]
@allykrupina Let's do vice versa: open a new PR; if it is OK we close this one with a reason and reference to the newly created one.

**Comment by allykrupina** [comment]
@OleksiyRudenko  Ok, I created a new branch and opened a new pull request (https://github.com/kottans/frontend-2019-homeworks/pull/212) for this task

**Comment by OleksiyRudenko** [comment]
Closing this PR for the reasons above.

**Pull request closed without merging**
