### PR TITLE
Object Oriented JS

### PR DESCRIPTION
**Pull request by mazvira**
### Object Oriented JS

[Demo](https://mazvira.github.io/frontend-nanodegree-arcade-game) |
[Code base](https://github.com/mazvira/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@mazvira Thank you for your submission. However this PR contains code and commits that are out of this PR scope and may cause conflicts on merge.

It is happened most likely as you branched off from another feature branch.

Please, check this repo [instructions](https://github.com/kottans/frontend-2019-homeworks/blob/master/README.md#submit-a-task)

Please, resolve the issue.

You may find this [guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b) helpful.

**Comment by mazvira** [comment]
Delete odd folder

**Comment by mazvira** [comment]
I will create now new PR. Will it be ok?

**Comment by mazvira** [comment]
New PR #326 because of irrelevant commits

**Pull request closed without merging**
