### PR TITLE
js-pre-oop

### PR DESCRIPTION
**Pull request by Eugene50**
###A-Tiny-JS-World

[Demo](https://eugene50.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Eugene50/a-tiny-JS-world/blob/master/index.js)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@Eugene50 I was looking at the possibility to skip the PR scope.
Unfortunately, we have to fix it.
We started a couple of times and [these instructions](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b) help others. In your case git history is too entangled making this task complicated.
I would suggest two options:
1) find a really early commit from upstream, even earlier than any of your commits and additions (this won't affect your other tasks because those are not interlinked)
2) create a new fork (you may fork many times from any repo) and be careful in merging strategies, i.e. not merge anything **into** master

What way would you prefer to proceed with?

You will benefit when master git better as this skill will be required in your future work.

Sorry for it took me time to suggest options, I've been figuring out simpler options than we had tried before.

**Comment by Eugene50** [comment]
Ok, i am ready to take this experience))
i think i can start with the first suggestion, and try to search the most recent commit. 
But how to made it? in which repo, frontend-2019-homeworks? or  a-tiny-js-world?

**Comment by OleksiyRudenko** [comment]
@Eugene50 Great choice :)
Seek in `frontend-2019-homeworks`. Find the most recent that comes right before any of your commits and post it short hash (SHA) here.

Our next step would be: **pair-cross-check**

**Comment by OleksiyRudenko** [comment]
@Eugene50 Thanks, looks a proper commit to develop further from.
 Please, do the following:
1.  `git checkout a9682dc`
1. `git checkout -b js-pre-oop`
1. add `submissions/Eugene50/a_tiny_js_world/index.js` with code as appropriate
1. commit changes
1. push to your origin
1. open a new PR

**Comment by Eugene50** [comment]
I have created new PR!)
But i think have the same situation with a Frogger PR, or i can now open new PR from the frogger branch?

**Comment by OleksiyRudenko** [comment]
@Eugene50 Cannot see Frogger PR.
My recommendation is to submit your future additions following the instructions above.
Commit a9682dc is a good point to start a new feature branch every time at.

**Pull request closed without merging**
