### PR TITLE
Frogger-oojs

### PR DESCRIPTION
**Pull request by Eugene50**
###Object Oriented JS(Frogger)

[Demo](https://eugene50.github.io/Frogger_OOP/) |
[Code base](https://github.com/Eugene50/Frogger_OOP)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by Eugene50** [comment]
I try to fix, hope now is correct!)

**Comment by OleksiyRudenko** [comment]
@Eugene50 Seems like you're still struggling. Did you try to follow the [guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b)? It worked for others.

If either part of the guide is not really clear, please, specify it here. Log of your commands, commands output and git tree logs (see below) will help to understand the issue.

Seems like you didn't find the proper commit shared by original repo and your fork in `master`. It is crucial to find it, so you can branch off at an appropriate point.

You will find `git logg -n25` command useful. To have it working add the following alias
`git config --global alias.logg "log --graph --full-history --all --color --pretty=format:\"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s\""`

Will you try once again?

**Comment by Eugene50** [comment]
тут уже проще на языке поближе!)
Возможно  ли что я сделал бэкап с этим коммитом и он потом при процедуре востановления появляеться снова?  я по гайду все сделал но пока не вышло(

**Comment by Eugene50** [comment]
я так понимаю что если я просто удалю ветку и снова ее создам это ничего не даст?

**Comment by OleksiyRudenko** [comment]
@Eugene50 Let's find out. It should be fixable.

Run the following command
`git config --global alias.logg "log --graph --full-history --all --color --pretty=format:\"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s\""`

It adds useful alias.

Then run `git logg -n25` and post output here.

**Comment by Eugene50** [comment]
Ok, this is the output
[output](https://github.com/Eugene50/other/blob/master/img/output.jpg)

**Comment by Eugene50** [comment]
i checked my branches, and  found many BACKUP...

[out_](https://github.com/Eugene50/other/blob/master/img/out_.png)

**Comment by OleksiyRudenko** [comment]
@Eugene50 
So, from [this log](https://github.com/Eugene50/other/blob/master/img/output.jpg) it comes that `upstream/master` is not in sync with both local `master`, and `origin/master`. The most recent commit shared by `upstream` and your fork is d00e9bf.

Please, complete instructions from [this section A](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b#a-reset-master) using the above as a shared commit SHA.

When the above is complete, please, post `git logg -n25` output here. Please, post text rather than a screenshot. `git bash` window offers copy/paste tools via context menu. Thanks.

You can later remove backup branches if you complete instructions from [this section D](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b#d-clean-up)

**Comment by Eugene50** [comment]
output:
 
d33e918        (origin/a-tiny-js-world, a-tiny-js-world) delete needless code
 b27c9dc        add files for tiny_world
 62f1747        (origin/frogger-oop-task, frogger-oop-task) add files for Frogge
-oop
   26c2205      Merge branch 'master' of https://github.com/kottans/frontend-201
-homeworks
\
 | * 0ca74fc    (backup-feature) add new comments
 | *   8f3295a  Merge branch 'master' of https://github.com/kottans/frontend-201
-homeworks
 | |\
 |/ /
/| /
 |/
 *   d00e9bf    (HEAD -> master, upstream/master, origin/master, origin/HEAD) Me
ge pull request #51 from justdevway/dom-api-task
 |\
 | * f8bff00    Restructured code after review
 | * f89a8f8    Fixed bugs according to review
 | * 6ce9f71    Fixed style bugs in modal window
 | * 886c5cc    js-dom - done
 * | 7d783ce    Js-frogger (#50)
 * | d78300a    Task js oop (#24)
 | |   1d46af0  (backup-frogger-oop-task) Merge branch 'master' into frogger-oop
task
\ \ \
 |/ /
 * |   a1fdf50  (backup-master) Merge pull request #38 from feroxes/froggen-game

**Comment by OleksiyRudenko** [comment]
@Eugene50 Thanks.
Add 3 back-ticks \`\`\` before log and another \`\`\` after. This will make log properly formatted.

Please, also make `git-bash` screen wider so lines do not wrap before running `git logg`

Thanks.

**Comment by OleksiyRudenko** [comment]
@Eugene50 Thanks for fixing your past post and apologies for not noticing it before - GitHub doesn't raise a notification when a post is updated.
From the history I can see there are more historical commits from your contributions the shared commit d00e9bf is added on the top of.
Sorry to tell you but we need to dig even deeper, otherwise the main repository (upstream) history will become chaotic.
Please, post here here the output of `git logg -n50` and mention me.
Thanks.

**Pull request closed without merging**
