### PR TITLE
memory-game

### PR DESCRIPTION
**Pull request by RomanovAleksander**
### Memory Game

[Demo](https://romanovaleksander.github.io/memory-game/) |
[Code base](https://github.com/RomanovAleksander/memory-game)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
_This is not a code review._

My impression from demo: when the second card opening is a matching card the flipping animation is different. Probably, you have two fragments of code responsible for flipping matching and non-matching cards, which is not really good, or some other business logic flaw.

**Comment by RomanovAleksander** [comment]
Ok, I'll try to fix.

**Comment by RomanovAleksander** [comment]
Can I create new pull request?

**Comment by RomanovAleksander** [comment]
Can I close pull request?

**Comment by OleksiyRudenko** [comment]
Yes, you can. Just give a reason for history and refer any other commit by its number preceded with `#`. Github will take care of cross-linking.

**Comment by RomanovAleksander** [comment]
Incorrectly sent a pull request, so closed it. #196

**Pull request closed without merging**
