### PR TITLE
create side menu

### PR DESCRIPTION
**Pull request by yulyasystem**
### side-menu-task

[Demo](https://suspicious-brown-2c203e.netlify.com/) |
[Code base](https://github.com/yulyasystem/kottans-frontend/tree/master/6%20task_js_dom/js-dom)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @yulyasystem! Great job! Let's make some improvements.

First things first: code should be well formatted. Please check and fix inconsistent indentations and remove empty lines. Also, every file should end with new line and console statements used for debugging should be removed before code is submitted.. For this small script you can do it manually, but better approach is to use your editor for this task. Check your editor's built-in code formatter. 

Global variables are a source of many bugs and should be generally avoided. Check your code and remove them.

Event delegation. It is very inefficient to add event listeners in a loop. Use event delegation and add one event listener to the containing element, instead of adding an event listener to every item in array (see line 21).

**Comment by yulyasystem** [comment]
I`ve made changes. Review please :)

**Comment by AMashoshyna** [comment]
Yes, I see, will answer later today =)

**Comment by AMashoshyna** [comment]
Ok, you did a great job formatting your code and implementing event delegation! However the thing with global variables is still not fixed. What I mean is you don't really need the variables `selectedLink`, `data` and `index` in global scope. Try to get rid of them. Let me know if you need help.

**Comment by AMashoshyna** [comment]
Great! I will merge the PR, but note this one thing as possible improvement. You use a pretty complex way to get element id:
```
    content = target.getAttribute("data-content");
    let arr = target.id.split('/');
    let index = arr[arr.length - 1];
```
As far as I can see, your IDs are already numbers. I thins you can use them directly and convert to integers with `+` sign or `Number` constructor.

**Pull request merged**
