### PR TITLE
OOP Exercise

### PR DESCRIPTION
**Pull request by AnnaGrynchuk**
### OOP Exercise

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@AnnaGrynchuk Thank you for your submission.
**OOP Exercise** is a task on its own. It is based on some code you already have but need to be submitted in a dedicated branch and its own sub-directory.
Please, follow the [instructions](https://github.com/kottans/frontend-2019-homeworks/blob/master/README.md#submit-a-task)

Please, also do not merge master into your feature branch for no reason as it makes repository history entangled. Please, update the PR with commits from your local machine, not via guthub web editor.

It is also important to provide links to a working demo and your own repository containing code, which also serves as your personal portfolio.

If you need any clarifications or need any support re above, please, let me know.

**Comment by AnnaGrynchuk** [comment]
@OleksiyRudenko, I need some help. It's not clear for me what should I do now with this PR. Can I use cherry-pick to relocate commit with OOP exercise to its own branch?

**Comment by OleksiyRudenko** [comment]
@AnnaGrynchuk Yes, sure you can cherry-pick once you have a new branch and code files in a dedicated folder.

**Comment by OleksiyRudenko** [comment]
@AnnaGrynchuk Let's go on in #339.
Closing this PR for the task's been resubmitted with #339

**Pull request closed without merging**
