### PR TITLE
Js oop frogger

### PR DESCRIPTION
**Pull request by o-msh**
### Object oriented JS

[Demo](https://o-msh.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/o-msh/frontend-nanodegree-arcade-game)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@o-msh Thank you for the submission.
Didn't look at your code yet.
Please, check yourself against following bullet-points:
 * [ ] it is OK to employ ES6 features like `const`, `let` etc.
 * [ ] OO is implemented using JS prototype chain object model (**not** ES6 classes syntax)
 * Requirements re **Constants**:
   * [ ] all numbers like block dimensions, initial locations are defined as constants
   * [ ] there are core contants and derived constants
         (e.g. `const FIELD_WIDTH = BLOCK_WIDTH * BLOCKS_NUMBER;`)
   * [ ] arrays of constants are also constants 
         (e.g. `const INITIAL_POSITIONS = [1,2,3,4].map(rowNumber => rowNumber * BLOCK_HEIGHT);`)
 * Requirements re **OOP**:
   * [ ] properties common for some classes are generalized into a base class
         (e.g. there is `Character` base class, which is extended by `Enemy` and `Player` classes)
   * [ ] class extension is implemented using `Subclass.prototype = Object.create(Superclass.prototype)`,
         not `Subclass.prototype = new Superclass(params);`;
         [Useful resource](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
   * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
         (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
         Hint: pass `Player` instance as an argument to every enemy
 * Most common mistakes
   * [ ] Make sure `target = condition ? valueWhenConditionTrue : valueWhenConditionFalse` is used instead of
         `condition ? target = valueWhenConditionTrue : target = valueWhenConditionFalse`;
         [Conditional (ternary) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)
         
Please, confirm all items above are positive. Please, ask a question if anything above requires clarification.

**Comment by o-msh** [comment]
Thank you for your comments. Please, rewatch again)

**Comment by OleksiyRudenko** [comment]
A note for myself: `*`

**Comment by o-msh** [comment]
With grouped configurations looks like better )

**Comment by OleksiyRudenko** [comment]
@o-msh Approved.
When you submit OOP Exercise PR, please, mention me and specify `*` in a comment.
Thanks.

**Pull request merged**
