### PR TITLE
friends-app

### PR DESCRIPTION
**Pull request by vladk96**
### Friends app

[Demo](https://vladk96.github.io/friends-app/) |
[Code base](https://github.com/vladk96/frontend-2019-homeworks/tree/friends-app/submissions/vladk96/friends-app)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@vladk96 Your PR contains commits out of PR scope, which causes conflicts.
Please, fix.
You may find this [guide](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b) helpful.

**Comment by vladk96** [comment]
@OleksiyRudenko Can you help me? I accidentally deleted my local repo which having all braches. I cloned my forked repo again and now this repo have only master branch. I don`t know how to fix the problem that is described above.

**Comment by OleksiyRudenko** [comment]
@vladk96 As far as I can see your branches (at least some, at least with some commits) are [on your fork](https://github.com/vladk96/frontend-2019-homeworks/branches).

Step 1. Can you pull required branches locally and check if they contain commits you expect them to have?

**Comment by vladk96** [comment]
@OleksiyRudenko Thank you. I figured it out. Now I will try to move `commit 416a7db` to another branch

**Pull request closed without merging**
