### PR TITLE
tiny-js-world - review P.S. war with git && github

### PR DESCRIPTION
**Pull request by Karasb888**
### tiny-js-world (pre oop)

https://github.com/Karasb888/a-tiny-JS-world
https://karasb888.github.io/a-tiny-JS-world/

The code is submitted in a dedicated feature branch.
Please, review.

1. After doing 6 step of Honey, I fixed it, I get this error _fatal: You are not currently on a branch._ 
and was needed to print  **git checkout master**
2. After **git pull upstream** (get synced with upstream part) I get, _You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line._
 And was able to specify branch name (master).
3. When I try to type classic **git push** (on pushing my feature forced branch to origin) I get 
_error: failed to push some refs to 'git@github.com:Karasb888/frontend-2019-homeworks.git'
hint: Updates were rejected because the tip of your current branch is behind_
And just push it forcedly **git push -f**
Thats what problems I got on fixing my repo via your guide.  Hope, I do all right=)

### CODE REVIEW

**Comment by Karasb888** [comment]
Also, maybe it be useful to add https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git and https://git-scm.com/docs/git-reflog links If someone delete their origin (origin in meaning - with code for task) branch. P.S. Thanks for help, review my code, and writing that guide=)

**Comment by OleksiyRudenko** [comment]
@Karasb888 [Thank you for beta-testing and detailed feedback](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b#credits).

**Comment by OleksiyRudenko** [comment]
@Karasb888 You did a great job resolving the conflict worth special recognition.

Here is your achievement badge: [Kottans-Student-Conflict-resolution%3D-mastered%20conflict%20resolution-brightgreen.svg)](https://github.com/kottans/kottans/blob/master/endorsements.md)

Please, provide me with a link to a document in your repo so I could PR the badge code into.

Congratulations on the skills level-up!

**Comment by Karasb888** [comment]
https://github.com/Karasb888/kottans-frontend Thanks, for helping!)

**Pull request merged**
