### PR TITLE
Js oop frogger

### PR DESCRIPTION
**Pull request by beta-version-profile**
_Complete the form below and remove this line._

### Fogger
[Demo](http://halting-snails.surge.sh) |
[Code base](https://github.com/beta-version-profile/frontend-2019-homeworks/tree/js-oop-frogger/submissions/beta-version-profile/js-oop-frogger/js)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@beta-version-profile, @house96 Well done, though there is yet space for improvements.

Initial impressions from demo per se only:
 * hero and enemies are not well aligned against field blocks
 * hero's step is 1/2 of block size, which seems too short
 * `Score : undefined` at the page top
 * `Level: '1` at the page bottom (`'` seems to be a typo bug)
 * Expectation (and AFAIR assignment tech requirements as well) is that hero's position will be instantly reset once hero reaches water, earning extra score or life
 * horizontal movement creates visual artifacts (please, see illustration below)

Will you fix anything before code review?

screenshot_14

**Comment by beta-version-profile** [comment]
Ok, thanks. I will correct later.

**Comment by beta-version-profile** [comment]
I fixed it

**Comment by OleksiyRudenko** [comment]
@zonzujiro thanks for mentioning me here. Have missed the update among other PRs.

**Pull request merged**
