### PR TITLE
Practical task DOM

### PR DESCRIPTION
**Pull request by zophrox**
### Practical task DOM

[Demo](https://zophrox.github.io/first-practice-dom/) |
[Code base](https://github.com/zophrox/first-practice-dom)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Shall we keep PRs #173 and #175 or this one?

**Comment by zophrox** [comment]
I can not figure out how to remove the 173 PR


пт, 28 груд. 2018 о 17:12 Anastasiya Mashoshyna <notifications@github.com>
пише:

**Comment by zonzujiro** [comment]
@zophrox will you finish this PR?

**Comment by zonzujiro** [comment]
AFAIU we merged another version of this PR. So I will close this one.

**Pull request closed without merging**
