### PR TITLE
friends-app by feroxes

### PR DESCRIPTION
**Pull request by feroxes**
### Friends App

[Demo](https://feroxes.github.io/friends_app/) |
[Code base](https://github.com/feroxes/frontend-2019-homeworks/tree/friends-app/submissions/feroxes/friends-app)

The code is submitted in a dedicated feature branch.
Please, review.

P.S. The only one problem I have, is the filter buttons doesn't work in search results. My brain is blowing. Can't understand how to do that.

### CODE REVIEW

**Comment by feroxes** [comment]
I apologize for the long response, but now I don’t have much time. I'll make all the edits next week.

**Comment by AMashoshyna** [comment]
Sure, no hurry! Please pull the latest changes from master branch before proceeding (I have deleted .DS_Store files)

**Comment by feroxes** [comment]
Hi!
All done. 
But I forgot pull the latest changes from master. Sorry. How can I fix my mistake?
And I have one question. 
You said: "Global variables are often cause of trouble and normally you should try to avoid them. "
Why i should avoid them? What trouble can they give me?

**Comment by AMashoshyna** [comment]
Global variables are considered bad practice because they are accessible to all scripts in the page and thus can be modified by any script. This makes your code unpredictable.
    Also global variables make the code harder to read. You need to go through the code to find where the variable comes from and what it depends on.

**Comment by AMashoshyna** [comment]
PR merged!

**Pull request merged**
